# Generated by Django 4.1 on 2022-08-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_Home', '0004_alter_book_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('senior', models.BooleanField(null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=25)),
                ('num_of_books', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
