# Generated by Django 4.1 on 2022-09-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
